config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  resources :quizzes
  root to: 'visitors#index'
  devise_for :users
  resources :users
  get  '/start_quiz/:id', to: 'quizzes#start_quiz'
  get  '/ask_question', to: 'quizzes#ask_question'
  post '/answer_question', to: 'quizzes#answer_question'
  get  '/show_results', to: 'quizzes#show_results'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  has_many :answers, dependent: :delete_all
  accepts_nested_attributes_for :answers, reject_if: lambda {|attributes| attributes['text'].empty?}

  # Could also go in initializers
  def self.max_answers
    4
  end

  def correct?(id)
    #If we pass the object, get the id
    if id.is_a? Answer
      id = id.id
    else
      # convert str to number
      if id.is_a? String
        id = id.to_i
      end
    end
    # For each answer
    answers.each do |ans|
      # if this is the right one
      if(ans.id == id)
        if(ans.correct)
          return true
        end
        return false
      end
    end
  return false
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new( quiz_id: params[:quiz])
    Question.max_answers.times{@question.answers.build}
  end

  # GET /questions/1/edit
  def edit
    #  Add any blank answers
    (@question.answers.count..Question.max_answers).each{@question.answers.build}
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    remove_blank_answers
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question.quiz, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_blank_answers
    for a in @question.answers do
      if a.text.empty?
        #a.destroy
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      remove_blank_answers
      if @question.update(question_params)
        format.html { redirect_to @question.quiz, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    quiz = @question.quiz
    @question.destroy
    respond_to do |format|
      format.html { redirect_to quiz, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:text, :url, :quiz_id, answers_attributes: [:id, :text, :correct, :url, :quiz_id], )
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_ask_question.html.erb
<div>
  <div>
    <% # Note:  Not caching a thumbnail slows this page down %>
    <div class="parent"><div class="img-container"><%= image_tag qs.url, "max-height" => "50" %></div></div>
    <strong><%=qs.text%></strong>
  </div>
  <% if qs.answers %>
    <table class="table table_hover"
    <% qs.answers.each{ |an| %>
      <%= render('answers/ask_answer_row', an: an) %>
    <% } %>
    </table>
  <% end%>
</div>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.fields_for :answers do |ans| %>
      <li>
        <div class="field">
          <%= ans.label :text %>
          <%= ans.text_field :text %>
          <%= ans.label :correct %>
          <%= ans.check_box :correct %>
        </div>
      </li>

    <% end %>

    <%= form.hidden_field :quiz_id, value: question.quiz_id %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div>
  <div>
    <strong><%=qs.text%></strong>
    <% # Note:  Not caching a thumbnail slows this page down %>
    <div class="parent"><div class="img-container"><%= image_tag qs.url, "max-height" => "50" %></div></div>
    [<%= link_to 'Edit Question', edit_question_url(qs) %>
    | <%= link_to 'Delete', question_url(qs), :method=>'delete' ,:confirm=>'Are you sure?' %>
    ]
  </div>
  <% if qs.answers %>
    <table class="table table_hover"
    <% qs.answers.each{ |an| %>
      <%# This took a bit of design.  Since almost all the info is in the quiz, the only thing you need to know for the score
            is what was selected. Which answer is correct is stored in the quiz.  Instead of duplicating the entire quiz for
            each instance, I keep the instance state in score and refer everything back to the quiz.
      %>
      <% if score %>
        <%= render('answers/answer_row', an: an, is_selected: score.is_selected(qs.id, an.id), is_correct: an.correct) %>
      <% else %>
        <%= render('answers/answer_row', an: an, is_selected: false, is_correct: an.correct) %>
      <% end %>
    <% } %>
    </table>
  <% end%>
</div>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', quiz_path(@question.quiz) %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Url</th>
      <th>Quiz</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.text %></td>
        <td><%= question.url %></td>
        <td><%= question.quiz %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @question.text %>
</p>

<p>
  <strong>Url:</strong>
  <%= @question.url %>
</p>

<p>
  <strong>Quiz:</strong>
  <%= @question.quiz %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>