config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  resources :quizzes
  root to: 'visitors#index'
  devise_for :users
  resources :users
  get  '/start_quiz/:id', to: 'quizzes#start_quiz'
  get  '/ask_question', to: 'quizzes#ask_question'
  post '/answer_question', to: 'quizzes#answer_question'
  get  '/show_results', to: 'quizzes#show_results'
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy, :add]

  def start_quiz
    @score = Score.new()
    @score.quiz_id = params[:id]
    @score.user=current_user
    @score.save
    # Keep id in session, but keep score server side for security
    session[:score_id]=@score.id
    set_current_question 0
    redirect_to '/ask_question'
  end

  def show_results
    @score=Score.find(session[:score_id])
    @quiz=@score.quiz
    render :show

  end

  def ask_question
    @score=Score.find(session[:score_id])
    @current_question = current_question
  end

  def answer_question
    @score=Score.find(session[:score_id])
    @question_index = current_question
    #byebug
    qs=@score.quiz.questions[current_question]
    correct = qs.correct?(params[:answer_id])
    @score.answer(qs.id.to_i, params[:answer_id].to_i, correct )
    @score.save
    set_current_question @question_index + 1
    if qs=@score.quiz.questions[current_question]
      redirect_to '/ask_question'
    else
      redirect_to '/show_results'
    end
  end

  def current_question
    i = session[:question_index] || 0
    return i
  end

  #So we can do next/prev/first/last in controller
  def set_current_question(qi)
    session[:question_index]=qi
    return qi
  end

# GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.find(user: current_user)
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    if current_user
      @quiz = Quiz.new(quiz_params)
      @quiz.user = current_user
    else
      flash[:error] = "Not signed in"
      redirect_to sign_in_url
    end


    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:name, :user_id)
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz, local: true) do |form| %>
  <% if quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quizzes/_quiz.html.erb
<% @editable ||= false #In case it's not set earlier %>
<% if @quiz.questions %>
  <% @quiz.questions.each{ |qs| %>
    <%= render('questions/question' , qs: qs, score: @score || nil ) %>
  <%}%>
<% end%>
<%= link_to "Add Question", new_question_path(quiz: @quiz),  class: "btn btn-lg btn-primary"  if not @score %>
<%= link_to "Back", user_path(@quiz.user),  class: "btn btn-lg btn-primary"  if @score %>
</div>

app/views/quizzes/ask_question.html.erb
Quiz is <%= @score.quiz_id %>
<%= form_tag(answer_question_path, method: "post") do %>
  <%= render('questions/ask_question' , qs: @score.quiz.questions[@current_question] ) %>
  <%= submit_tag('Next') %>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form', quiz: @quiz %>

<p>
  <%  @editable = true %>
  <%= render 'quiz' %>
</p>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', user_url(@quiz.user) %>

app/views/quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.name %></td>
        <td><%= quiz.user %></td>
        <td><%= link_to 'Show', quiz %></td>
        <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz', new_quiz_path %>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @quiz.name %>
</p>
<p>
  <%= render('quiz') %>
</p>


<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', user_url(@quiz.user) %>