config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  resources :quizzes
  root to: 'visitors#index'
  devise_for :users
  resources :users
  get  '/start_quiz/:id', to: 'quizzes#start_quiz'
  get  '/ask_question', to: 'quizzes#ask_question'
  post '/answer_question', to: 'quizzes#answer_question'
  get  '/show_results', to: 'quizzes#show_results'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :quizzes, dependent: :delete_all
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/views/users/_user.html.erb
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>
<p>Quizzes I created</p>
<p><%= link_to "Create New Quiz", new_quiz_url %></p>
<% if @user.quizzes %>
  <table class="table table-hover">
    <% @user.quizzes.each { |qz| %>
      <tr>
        <td><%=qz.name%></td>
        <td><%= link_to 'View', qz%></td>
        <td><%=link_to 'Edit', edit_quiz_url(qz) %></td>
        <td><%= link_to 'Start Quiz','/start_quiz/'+qz.id.to_s %></td>
      </tr>
  <% } %>
</table>
<% end %>